# This file was generated by GoReleaser. DO NOT EDIT.
cask "osaat" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b7ecdc50d001a59424b1f92346742e616cb675098efa9fe758d25587a127b943"
      url "https://github.com/simtabi/osaat/releases/download/v#{version}/osaat_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8b94e8faa9f68137eb9974fc544f85088cb4d3a109d071e22472093040300bf"
      url "https://github.com/simtabi/osaat/releases/download/v#{version}/osaat_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84c34e6993e8cd6febccff8914897f951dd711cb5cdd5afd516088afcfc0fe16"
      url "https://github.com/simtabi/osaat/releases/download/v#{version}/osaat_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19de17cc23015856e32974f32aab4a8dbc4737f0c814050219e786cebeb13411"
      url "https://github.com/simtabi/osaat/releases/download/v#{version}/osaat_linux_amd64.tar.gz"
    end
  end

  name "osaat"
  desc "Audit and back up installed applications on macOS, Linux, and Unix."
  homepage "https://opensource.simtabi.com/products/simtabi/osaat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "osaat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/osaat"],
        sudo: false
    end
  end

  # No zap stanza required
end
